name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install tools used in tests
      run: |
        npm install -g pnpm
    - name: Run tests
      run: dash run-tests.sh
